rest:
  ssl: true
  host: dspace2023.ort.edu.uy
  port: 443
  nameSpace: /server

languages:
  - code: en
    label: English
    active: true
  - code: ca
    label: Català
    active: false
  - code: cs
    label: Čeština
    active: false
  - code: de
    label: Deutsch
    active: false
  - code: es
    label: Español
    active: true
  - code: fr
    label: Français
    active: false
  - code: gd
    label: Gàidhlig
    active: false
  - code: lv
    label: Latviešu
    active: false
  - code: hu
    label: Magyar
    active: false
  - code: nl
    label: Nederlands
    active: false
  - code: pl
    label: Polski
    active: false
  - code: pt-PT
    label: Português
    active: false
  - code: pt-BR
    label: Português do Brasil
    active: true
  - code: fi
    label: Suomi
    active: false
  - code: sv
    label: Svenska
    active: false
  - code: tr
    label: Türkçe
    active: false
  - code: kk
    label: Қазақ
    active: false
  - code: bn
    label: বাংলা
    active: false
  - code: hi
    label: हिंदी
    active: false
  - code: el
    label: Ελληνικά
    active: false
  - code: uk
    label: Yкраї́нська
    active: false

themes:
  - name: ort
    headTags:
      - tagName: link
        attributes:
          rel: icon
          href: https://www.ort.edu.uy/innovafront/theme/si2/favicon.ico
          sizes: any